### ISSUE TITLE
WebVTT support

### ISSUE THREAD

**Issue by ole** [ole/transcribe#2]
Continuing the discussion from [SwiftCommunityPodcast #15](https://github.com/SwiftCommunityPodcast/podcast/issues/15#issuecomment-460089441).

[Wikipedia: WebVTT](https://en.m.wikipedia.org/wiki/WebVTT)
[W3C: WebVTT Spec](https://w3c.github.io/webvtt/)

I think this is a great idea for moving forward. We'd need:

- Code for converting an `AmazonTranscribe.Transcript` value to a WebVTT-compatible string (should be quite easy).
- Code for parsing a WebVTT file into a general data structure. This would be great to have because it would allow us to edit the WebVTT transcript in WebVTT (which looks very editable with a text editor) and then read the edited file back in for possible conversion to other formats.
- The existing `AmazonTranscribe.Transcript` struct may be generalizable to act as a general data structure for storing a transcript, but I tend to think using a separate, more general data structure would be easier. For example, the distinction between punctuation characters and spoken words made by Amazon Transcribe isn't really important.

**Comment by JulianKahnert** [comment]
Hey @ole very nice to here that! I will look into that tomorrow. Could you elaborate your requirements/ideas behind the „general data structure“? I just want to make sure that I can start in the right direction. 🙂

**Comment by ole** [comment]
@JulianKahnert Great.

> Could you elaborate your requirements/ideas behind the „general data structure“?

I don't have anything specific in mind. And may "general" was the wrong word. What I meant was:

1. The existing data structures are probably fairly Amazon-Transcribe-specific in some areas, so I think it makes sense to create a separate `WebVTT` struct that better maps to the requirements of that format.

2. As we incorporate multiple input and/or output formats, it's possible (maybe even likely) that we come up with a single data structure that can be used as a general internal representation for a transcript. If that happens, I'm not tied to any of the existing code, so feel free to change things around. But maybe this is a second step anyway.
